export const FILE_CATEGORIES = {
  audio: {
    label: 'Аудио',
    tag: '<audio controls src="...">',
    tool: 'HTML5 Audio Player / Web Audio API',
    extensions: ['mp3', 'wav', 'ogg', 'aac', 'flac', 'm4a', 'wma'],
  },
  video: {
    label: 'Видео',
    tag: '<video controls src="...">',
    tool: 'HTML5 Video Player / Video.js',
    extensions: ['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv', 'flv', 'wmv'],
  },
  image: {
    label: 'Изображение',
    tag: '<img src="..." alt="...">',
    tool: 'HTML5 Image Tag / Canvas / Lightbox',
    extensions: [
      'jpg',
      'jpeg',
      'png',
      'gif',
      'svg',
      'webp',
      'bmp',
      'ico',
      'avif',
    ],
  },
  document: {
    label: 'Документ / Текст',
    tag: '<iframe src="..."> или <pre>',
    tool: 'PDF.js / Monaco Editor / Markdown Viewer / Text Reader',
    extensions: [
      'pdf',
      'txt',
      'doc',
      'docx',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'csv',
      'json',
      'xml',
      'md',
      'html',
      'css',
      'js',
    ],
  },
  archive: {
    label: 'Архив',
    tag: '<a download href="...">',
    tool: 'JSZip / Download Link',
    extensions: ['zip', 'rar', '7z', 'tar', 'gz', 'bz2'],
  },
};
